In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
b=np.zeros(2)
b

array([0., 0.])

In [3]:
c=np.ones(3)
c

array([1., 1., 1.])

In [4]:
d=np.empty(3)
d

array([1., 1., 1.])

# creating an arrey

In [5]:
import numpy as np

In [6]:
food=np.array(["pakora","Samosa","Raita"])
food

array(['pakora', 'Samosa', 'Raita'], dtype='<U6')

In [7]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [8]:
type(price)

numpy.ndarray

In [9]:
type(food)

numpy.ndarray

In [10]:
len(price)

3

In [11]:
price[0:2]

array([5, 5])

In [12]:
price.mean()

5.0

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.empty(5)

array([8.55279685e-312, 0.00000000e+000, 9.34562258e-307, 5.38531554e-322,
       0.00000000e+000])

In [17]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [21]:
np.linspace(1,100,num=50)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [22]:
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

# Array functions

In [26]:
a=np.array([10,34,34.35,66,87,35,8653,22.67])
a

array([  10.  ,   34.  ,   34.35,   66.  ,   87.  ,   35.  , 8653.  ,
         22.67])

In [28]:
b=np.array([10.2,3.4,882,43.5])
b

array([ 10.2,   3.4, 882. ,  43.5])

In [30]:
np.concatenate((a,b))

array([1.000e+01, 3.400e+01, 3.435e+01, 6.600e+01, 8.700e+01, 3.500e+01,
       8.653e+03, 2.267e+01, 1.020e+01, 3.400e+00, 8.820e+02, 4.350e+01])

In [33]:
c.sort()
c

array([1., 1., 1.])

# 2-D

In [43]:
a=np.array([[1,2],[5,4]])
a

array([[1, 2],
       [5, 4]])

In [40]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [44]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [47]:
np.concatenate((a,b),axis=1)

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

# Markdown